---
driver:
  name: dokken
  chef_version: latest
  privileged: true

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get -y install net-tools less nginx && /usr/bin/apt-get clean
      ports:
        - "2222:22"
      hostname: nginx-test
      dns:
        - 8.8.8.8

suites:
  - name: default
    run_list:
      - recipe[enginx::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
